{% set name = "yandexcloud" %}
{% set version = "0.201.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yandexcloud-{{ version }}.tar.gz
  sha256: 71df4d5420b37fb3916244ef9bc535be7e784a327b1da101bb3f5587c140e31f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - cryptography >=2.8
    - googleapis-common-protos >=1.53.0
    - grpcio >=1.38.1
    - protobuf <3.21
    - pyjwt >=1.7.1
    - python >=3.7
    - requests >=2.22.0
    - six >=1.14.0

test:
  imports:
    - yandex
    - yandex.cloud
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/yandex-cloud/python-sdk
  summary: The Yandex.Cloud official SDK
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/yandex-cloud/python-sdk
  doc_url: https://github.com/yandex-cloud/python-sdk

extra:
  recipe-maintainers:
    - xylar
