{% set name = "yandexcloud" %}
{% set version = "0.238.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yandexcloud-{{ version }}.tar.gz
  sha256: 1c25ef5283d893ef434be168c6e0dcb8255b1e05d07b474a8550c16f0a5beb0e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - cryptography >=2.8
    - grpcio >=1.56.2
    - protobuf >=4.23.4
    - googleapis-common-protos >=1.59.1
    - pyjwt >=1.7.1
    - python >=3.7
    - requests >=2.22.0
    - six >=1.14.0

test:
  imports:
    - yandex
    - yandex.cloud
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/yandex-cloud/python-sdk
  summary: The Yandex.Cloud official SDK
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/yandex-cloud/python-sdk
  doc_url: https://github.com/yandex-cloud/python-sdk

extra:
  recipe-maintainers:
    - xylar
